#!/bin/bash

# Kill XFCE session components
pkill -f xfce4-session
pkill -f xfwm4
pkill -f xfsettingsd
pkill -f xfce4-panel
pkill -f xfdesktop
pkill -f Thunar

# Kill Xephyr (all variants)
pkill -f "Xephyr"

# Remove stale locks
rm -f /tmp/.X2-lock
rm -f /tmp/.X11-unix/X2

sleep 0.2
